refactor: use prisma types front-end-front-office
2019-2020-ps6/2022-2023-ps6-webonjour pull request #254
Opened 2023-05-20 17:42 UTC by Apoorva64

Ref: #253

2023-05-20 18:34 UTC, Apoorva64 commented
# ☁️ Nx Cloud Report

CI is running/has finished running commands for commit 9b3e0465187f5029d5995b9e2b15f619bdef45a5. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=640ee8fb56da4d6500e89717&branchName=254,253-refactor-migrate-util-interface-types-quiz-type-to-prisma-types)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`nx affected --target=lint --parallel=3`](https://cloud.nx.app/runs/6ckfZQvxst)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-05-20 18:40 UTC, Guekka reviewed
How does `Prisma.QuestioNGetPayload` work?
We also might want to add a function, you have duplicated code

2023-05-21 09:43 UTC, Apoorva64 commented
> How does `Prisma.QuestioNGetPayload` work?
> We also might want to add a function, you have duplicated code

Rtfm xD
https://www.prisma.io/docs/concepts/components/prisma-client/advanced-type-safety/operating-against-partial-structures-of-model-types

2023-05-21 10:05 UTC, Guekka commented
> Rtfm 

Alright, I deserve it

2023-05-21 10:06 UTC, Guekka requested changes
Refactor out this bit
```ts
Prisma.QuestionGetPayload<{
    include: {
      answers: true;
      clues: true;
    };
  }>;
```

2023-05-21 12:07 UTC, ArnaudDumanois submitted a review, later dismissed
lgtm

2023-05-21 15:28 UTC, Guekka commented
Looks like there's a CI failure. Working on it

2023-05-21 18:48 UTC, Apoorva64 commented on apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answers/question-detail-answers.component.ts
> +      id: -1,
Should use Input type

2023-05-22 06:48 UTC, ArnaudDumanois submitted a review, later dismissed
lgtm

2023-05-22 06:52 UTC, ozeliurs commented on apps/front-end/back-office/src/app/components/quiz-creation/question-detail-main/question-detail-main.component.spec.ts
> +          id: 1,
wtf dude

2023-05-22 06:55 UTC, ozeliurs commented on libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
> +    function deleteQuiz(id: number | undefined) {
cannot delete undefined quiz

2023-05-22 06:56 UTC, ozeliurs commented on libs/data-access-fake-backend/src/lib/interceptors/fake-backend.interceptor.ts
> +import { Auth, Patient, Quiz as Q } from '@webonjour/util-interface';
Do not use single letter variable

2023-05-22 07:06 UTC, Guekka commented on apps/front-end/back-office/src/app/components/quiz-creation/question-detail-answers/question-detail-answers.component.ts
> +      id: -1,
Will do in another issue

2023-05-22 07:08 UTC, Guekka commented on apps/front-end/back-office/src/app/components/quiz-edition/quiz-edition.component.ts
> +  quiz!: Prisma.QuizGetPayload<Quiz.QuizWithQuestions>;
Use the above `Question` type

2023-05-22 07:17 UTC, Guekka approved these changes

2023-05-22 07:17 UTC, merged