feat: question crud
2019-2020-ps6/2022-2023-ps6-webonjour pull request #288
Opened 2023-05-31 12:27 UTC by Guekka

Fix #287

2023-05-31 12:28 UTC, Apoorva64 commented
# ☁️ Nx Cloud Report

> ⚠️ Important: This organization has reached the limit of the FREE Plan and will be disabled at the end of the month. Remote caching and distributed task execution will no longer work. Your CI may stop working.
        

CI is running/has finished running commands for commit 81b82caab5b6b246055845f21d6f7accfb7118ad. As they complete they will appear below. Click to see the status, the terminal output, and the build insights.

[📂 See all runs for this branch](https://cloud.nx.app/branch?workspaceId=640ee8fb56da4d6500e89717&branchName=288,287-add-crud-for-question)

---


<details>
<summary>✅ Successfully ran 1 target </summary>

- [`nx affected --target=lint,test,build --parallel=3`](https://cloud.nx.app/runs/GwLq9gi6ke)
</details>

---

Sent with 💌 from [NxCloud.](https://nx.app)

2023-05-31 12:42 UTC, Apoorva64 requested changes

2023-05-31 12:42 UTC, Apoorva64 commented on apps/backend/api/src/main.ts
> +app.use('/api/question', questionRouter);
Should be in plural

2023-05-31 14:21 UTC, ArnaudDumanois approved these changes, later dismissed
lgtm

2023-05-31 16:48 UTC, ozeliurs approved these changes
LGTM

2023-06-01 18:50 UTC, Apoorva64 approved these changes

2023-06-01 18:50 UTC, merged